# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app - PaulHaefeliv2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Prepare deployment folder
        run: |
          mkdir -p deploy
          cp -r .next public package.json package-lock.json deploy/

      - name: Upload pre-built artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1387ED3058D2449CB9186EBA8F9820E4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A24B1184B33F4586BC99EE49BA46DA6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4ABAACAEDB344C20BBBB906A04E2D9A4 }}

      - name: Deploy pre-built app to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PaulHaefeliv2'
          slot-name: 'Production'
          package: deploy/
